"""CustomerAtlas Enterprise Canonical Utilities Package."""

from .formatting import (
    format_number,
    format_currency,
    format_percent,
    format_brl,
    format_pct,
    format_num,
)
from .styling import (
    load_css,
    style_chart,
    chart,
    CHART_COLORWAY,
    COLOR_PRIMARY,
    COLOR_CYAN,
    COLOR_PURPLE,
    COLOR_AMBER,
    COLOR_RED,
    COLOR_GREEN,
    COLOR_SLATE,
    PLOT_CONFIG,
)
from .validation import (
    validate_customer_dataframe,
    validate_customer_id,
    REQUIRED_CUSTOMER_COLUMNS,
)
from .logging_config import logger, setup_logger
from .exceptions import (
    CustomerAtlasError,
    DataValidationError,
    DataLoadError,
    ModelError,
    ModelLoadError,
    ModelInferenceError,
    ConfigurationError,
    AuthenticationError,
    AuthorizationError,
    ResourceNotFoundError,
    TenantIsolationError,
)
from .helpers import safe_float, safe_int, safe_str, calculate_pareto_cutoff, calculate_data_snapshot_info

__all__ = [
    "format_number",
    "format_currency",
    "format_percent",
    "format_brl",
    "format_pct",
    "format_num",
    "load_css",
    "style_chart",
    "chart",
    "CHART_COLORWAY",
    "COLOR_PRIMARY",
    "COLOR_CYAN",
    "COLOR_PURPLE",
    "COLOR_AMBER",
    "COLOR_RED",
    "COLOR_GREEN",
    "COLOR_SLATE",
    "PLOT_CONFIG",
    "validate_customer_dataframe",
    "validate_customer_id",
    "REQUIRED_CUSTOMER_COLUMNS",
    "logger",
    "setup_logger",
    "CustomerAtlasError",
    "DataValidationError",
    "DataLoadError",
    "ModelError",
    "ModelLoadError",
    "ModelInferenceError",
    "ConfigurationError",
    "AuthenticationError",
    "AuthorizationError",
    "ResourceNotFoundError",
    "TenantIsolationError",
    "safe_float",
    "safe_int",
    "safe_str",
    "calculate_pareto_cutoff",
    "calculate_data_snapshot_info",
]
