"""Compatibility re-export of canonical styling utilities from utils.styling."""

from utils.styling import (
    COLOR_PRIMARY,
    COLOR_PRIMARY_HOVER,
    COLOR_CYAN,
    COLOR_PURPLE,
    COLOR_AMBER,
    COLOR_RED,
    COLOR_GREEN,
    COLOR_SLATE,
    COLOR_SECONDARY,
    COLOR_MUTED,
    COLOR_BORDER,
    COLOR_SURFACE,
    COLOR_PAGE_BG,
    CHART_COLORWAY,
    PLOT_CONFIG,
    load_css,
    style_chart,
    chart,
)

__all__ = [
    "COLOR_PRIMARY",
    "COLOR_PRIMARY_HOVER",
    "COLOR_CYAN",
    "COLOR_PURPLE",
    "COLOR_AMBER",
    "COLOR_RED",
    "COLOR_GREEN",
    "COLOR_SLATE",
    "COLOR_SECONDARY",
    "COLOR_MUTED",
    "COLOR_BORDER",
    "COLOR_SURFACE",
    "COLOR_PAGE_BG",
    "CHART_COLORWAY",
    "PLOT_CONFIG",
    "load_css",
    "style_chart",
    "chart",
]
